require "user.alpha"
require "user.colorscheme"
require "user.debug.init"
require "user.keymaps"
require "user.nvim-tree"
require "user.options"
require "user.packages"
-- require "user.project"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
