require "user.packages"
require "user.alpha"
require "user.barbar"
require "user.colorscheme"
require "user.comment"
require "user.illuminate"
require "user.indentline"
require "user.trouble"
require "user.keymaps"
require "user.lualine"
require "user.nvim-tree"
require "user.options"
<<<<<<< HEAD
require "user.project"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
require "user.dap"
=======
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
require "user.coc"

>>>>>>> 366b617e2dbdc8ce002deff1415c3b2d158ae8c9
