require "user.packages"
require "user.alpha"
require "user.barbar"
require "user.colorscheme"
require "user.comment"
require "user.illuminate"
require "user.indentline"
require "user.trouble"
require "user.keymaps"
require "user.lualine"
require "user.nvim-tree"
require "user.options"
require "user.telescope"
require "user.treesitter"
require "user.whichkey"
require "user.coc"

